version: '2.1'

services:
  pup:
    build:
      context: .
#    image: hmcts/dm-store:latest
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pup-postgres-db:5432/pup
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      # these environment variables are used by java-logging library
      - AZURE_STORAGE_CONNECTION_STRING=false
      - ENABLE_CRON=false
      - ENABLE_UPLOAD_CSV=false
#      - ROOT_APPENDER=JSON_CONSOLE
#      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=pup-ref
      - REFORM_TEAM=refrence-data
      - REFORM_ENVIRONMENT=docker
    links:
     - pup-postgres-db
    depends_on:
     - pup-postgres-db
    ports:
    - $SERVER_PORT:8080

  pup-postgres-db:
      image: postgres
      restart: always
      environment:
      - POSTGRES_USER=pup
      - POSTGRES_PASSWORD=pup
      - POSTGRES_DB=pup
