spring:
  application:
    name: Professional User Profile
#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pup}
#    username: ${SPRING_DATASOURCE_USERNAME:pup}
#    password: ${SPRING_DATASOURCE_PASSWORD:pup}

reform:
  idam:
    api:
      baseUrl: ${IDAM_USER_BASE_URI:http://localhost:4501}
  s2s:
    api:
      baseUrl: ${IDAM_S2S_BASE_URI:http://localhost:4502}


info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:evidence}
    name: ${PACKAGES_NAME:dm-store}
#    version: ${PACKAGES_VERSION:unknown}

health:
  status:
    order:
    - FATAL
    - DOWN
    - UNKNOWN
    - UP
  disk:
    threshold: ${HEALTH_DISK_THRESHOLD:262144000}

management:
  endpoints:
    web:
      base-path: '/'


#endpoints:
#  health:
#    sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}
#  info:
#    sensitive: ${ENDPOINTS_INFO_SENSITIVE:false}

toggle:
  includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
  includes2shealth: ${ENABLE_S2S_HEALTH_CHECK:false}
