---
version: '2.1'

services:

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:1620c9973d85ca622904ecbf01c47a4abb91f7c9
    command: --wait-for-database 60
    environment:
      - IDAM_SUPERUSER_EMAIL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_PROFILES_ACTIVE=test
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_AUTHENTICATION_WEB_HOST=https://idam-authentication-web:8000
      - IDAM_REGISTRATION_WEB_HOST=https://idam-registration-web:8000
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_REGISTRATION_WEB=QM5RQQ53LZFOSIXJ
      - http_proxy
      - https_proxy
      - no_proxy
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=idam-api
      - REFORM_TEAM=cc
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=idam
      - PACKAGES_NAME=idam
      - PACKAGES_VERSION=unkown
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest

  smtp-server:
    image: mailhog/mailhog

  service-auth-provider-app:
    image: hmcts/service-auth-provider-app:latest
    environment:
      - AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_EM_GW=AAAAAAAAAAAAAAAA
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-app
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-app
      - PACKAGES_VERSION=unkown
